// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgres://fbf528c5542e8c9c996730de9ab05aa74f7930557e8038dba5a9b58071dbc7f9:sk_1Kcj471g5_us248OhoGiz@pooled.db.prisma.io:5432/postgres?sslmode=require",
  },
});
